### ISSUE TITLE
Add CITATION.cff and a badge to README.md

### ISSUE THREAD

**Issue by egorsmkv** [egorsmkv/tts_uk#9]
```
cff-version: 1.2.0
message: "If you cite this repository, please cite it as below."
authors:
- family-names: "Smoliakov"
  given-names: "Yehor"
  orcid: "https://orcid.org/0000-0002-8272-2095"
title: "High-fidelity speech synthesis for Ukrainian using modern neural networks."
version: 1.3.5
doi: 
date-released: 2025-03-04
url: "https://github.com/egorsmkv/tts_uk"
```
